language: node_js
node_js:
  - "12"

# Remove shallow cloning for Sonar analysis
git:
  depth: false

branches:
  only:
  - master

after_success:
  - npm run coverage:send
  - sonar-scanner

addons:
  sonarcloud:
    organization: "daniel-duarte"
    token:
      secure: $SONAR_TOKEN
