language: node_js
node_js:
  - "12"

branches:
  only:
  - master

after_success:
  - npm run coverage:send

addons:
  sonarcloud:
    organization: "daniel-duarte"
    token:
      secure: $SONAR_TOKEN

script:
  - sonar-scanner
